# Generated by Django 5.0.6 on 2026-06-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_wallet', 'Mobile Wallet'), ('cheque', 'Cheque')], max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=120, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=16)),
                ('profit_portion', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('principal_portion', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financing_app.installment')),
            ],
        ),
    ]
